spring:
  application:
    name: BootIOCProj11-LayeredApp-MiniProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rohith
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql:///spring_two_batch
    username: root
